---
channels:
    1:
        active: true
        color: FF0000
        end: 63418.0
        label: '0'
        max: 63418.0
        min: 0.0
        start: 0.0
    2:
        active: true
        color: 00FF00
        end: 64082.0
        label: '1'
        max: 64082.0
        min: 0.0
        start: 0.0
    3:
        active: true
        color: 0000FF
        end: 63708.0
        label: '2'
        max: 63708.0
        min: 0.0
        start: 0.0
greyscale: false
version: 2
